name: Auto Update Blog Content

on:
  schedule:
    - cron: '0 0 * * 1' # Berjalan setiap hari Senin jam 12 malam
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python autoblog.py

      - name: Commit and Push
        run: |
          git config --global user.name 'SakaAutoBot'
          git config --global user.email 'bot@saka.com'
          git add .
          git commit -m "Auto-generate new health articles"
          git push
